# -*- coding: utf-8 -*-
"""Final data preprocessing File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MfWSU-VKKwbfpP-O8gGnzABKSDM5cPG
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/aiml project /MNC Probability Analyzer (Responses) (1).xlsx'

import pandas as pd
df = pd.read_excel(file_path)


print(df.shape)

df.head()

df = df.drop('Email ID', axis=1, errors='ignore')

df = df.drop('SAP ID', axis=1, errors='ignore')

df = df.drop('Timestamp', axis=1, errors='ignore')

print(df.columns.tolist())

print(df.shape)

import pandas as pd


tech_col = 'Which technical skills do you have?'
other_col = 'Other skills: '

if tech_col in df.columns and other_col in df.columns:

    def count_skills(series):
        return series.fillna('').astype(str)\
                     .apply(lambda x: len([s.strip() for s in x.split(',') if s.strip()]))


    df['Total Skills'] = count_skills(df[tech_col]) + count_skills(df[other_col])


    df = df.drop([tech_col, other_col], axis=1)

    print(df.head())
else:
    print("Skill-related columns are not found. Please check column names.")

print(df.columns.tolist())



df = df.iloc[1:].reset_index(drop=True)


print(df.head())



df.shape



df.shape

df.head()





df.columns.tolist()



df.head()

df = df.drop('Other Certifications', axis=1, errors='ignore')

df = df.drop('Platform Ratings', axis=1, errors='ignore')

df.columns



df.head(40)

df['Technical Projects'] = df['Technical Projects'].fillna(0)
df['Internships'] = df['Internships'].fillna(0)

df.head(40)

name_to_drop = "Poorvi Arora"
print(f"Dropping: {name_to_drop}")
df = df[df['Full Name'] != name_to_drop].reset_index(drop=True)

name_to_drop = "Saksham Chawla"
print(f"Dropping: {name_to_drop}")
df = df[df['Full Name'] != name_to_drop].reset_index(drop=True)

name_to_drop = "Praanjal Jain"
print(f"Dropping: {name_to_drop}")
df = df[df['Full Name'] != name_to_drop].reset_index(drop=True)

name_to_drop = "Parag Goyal"
print(f"Dropping: {name_to_drop}")
df = df[df['Full Name'] != name_to_drop].reset_index(drop=True)



df.loc[df['Full Name'] == 'Arnav Sharma'	, 'LeetCode Solved'] = 25


df.loc[df['Full Name'] == 'Siya Chauhan'	, 'LeetCode Solved'] = 25
df.loc[df['Full Name'] == 'Siya Chauhan'	, 'Total Problems Solved'] = 400

df.head(40)







from sklearn.preprocessing import MinMaxScaler


numeric_cols = ['CGPA', '10th %', '12th %']


df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')


scaler = MinMaxScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])


print(df[numeric_cols].head())

from sklearn.preprocessing import MinMaxScaler


cols_to_normalize = ['Technical Projects', 'Internships', 'Total Problems Solved', 'CGPA', '10th %', '12th %']


scaler = MinMaxScaler()


df[cols_to_normalize] = scaler.fit_transform(df[cols_to_normalize])


print(df[cols_to_normalize].head())

df['Google_Readiness'] = (0.4 * df['LeetCode Solved'] +
                          0.3 * df['Technical Projects'] +
                          0.2 * df['Total Problems Solved'] +
                          0.1 * df['CGPA'])

df['Amazon_Readiness'] = (0.35 * df['LeetCode Solved'] +
                          0.25 * df['Technical Projects'] +
                          0.25 * df['Internships'] +
                          0.15 * df['CGPA'])

df['Infosys_Readiness'] = (0.3 * df['CGPA'] +
                           0.2 * df['10th %'] +
                           0.2 * df['12th %'] +
                           0.3 * df['Technical Projects'])

df['Microsoft_Readiness'] = (0.4 * df['Technical Projects'] +
                             0.3 * df['LeetCode Solved'] +
                             0.2 * df['Total Problems Solved'] +
                             0.1 * df['CGPA'])


readiness_cols = ['Google_Readiness', 'Amazon_Readiness', 'Infosys_Readiness', 'Microsoft_Readiness']
for col in readiness_cols:
    df[col] = df[col].clip(0, 1)


print(df[readiness_cols].head())



def suggest_improvements(row):
    suggestions = []


    if row['Google_Readiness'] < 0.3:
        suggestions.append('Improve DSA, Projects, and system design skills')
    elif row['Google_Readiness'] < 0.6:
        suggestions.append('Work on DSA, focus more on problem-solving, and contribute to projects')


    if row['Amazon_Readiness'] < 0.3:
        suggestions.append('Work on Competitive Coding, Improve Internship Experience, and Data Structures')
    elif row['Amazon_Readiness'] < 0.6:
        suggestions.append('Focus on competitive coding, internships, and system design')


    if row['Infosys_Readiness'] < 0.3:
        suggestions.append('Focus on Academics (CGPA, 10th, 12th), work on more projects, improve technical skills')
    elif row['Infosys_Readiness'] < 0.6:
        suggestions.append('Improve Academics, work on more projects, and focus on coding skills')

    if row['Microsoft_Readiness'] < 0.3:
        suggestions.append('Focus on Projects, LeetCode practice, and DSA')
    elif row['Microsoft_Readiness'] < 0.6:
        suggestions.append('Improve Projects, LeetCode practice, and algorithm knowledge')

    if row['Comm Skills (1-5)'] < 4:
        suggestions.append('Improve Communication Skills (Focus on clarity and confidence in speaking)')

    if row['Public Speaking'] < 4:
        suggestions.append('Enhance Public Speaking Skills (Practice presentations, engage in debates)')

    if row['Teamwork Experience'] < 3:
        suggestions.append('Work on Team Collaboration (Participate in group projects or team-based activities)')

    if row['Total Skills'] < 10:
        suggestions.append('Broaden Technical and Soft Skills (Expand your project portfolio and collaborate in teams)')

    if not suggestions:
        return "Good to go!"
    else:
        return '; '.join(suggestions)

df['Suggested_Improvements'] = df.apply(suggest_improvements, axis=1)

df[['Google_Readiness', 'Amazon_Readiness', 'Infosys_Readiness', 'Microsoft_Readiness',
    'Comm Skills (1-5)', 'Public Speaking', 'Teamwork Experience', 'Total Skills', 'Suggested_Improvements']].head()

df.head(40)

import pandas as pd

experience_columns = ['Technical Projects', 'Internships', 'Open Source Contribution',
                      'Freelancing Experience', 'Certifications', 'Public Speaking',
                      'Teamwork Experience']

df[experience_columns] = df[experience_columns].fillna(0)


print(df[experience_columns].head())



import pandas as pd


missing_values = df.isnull().sum().sum()

if missing_values > 0:
    print(f"Dataset contains {missing_values} missing values.")
else:
    print("No missing values in the dataset.")

df.to_excel(file_path.replace('.csv', '.xlsx'), index=False)

from google.colab import files


files.download(file_path)





