# -*- coding: utf-8 -*-
"""MODEL TRANING final  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M70t5ZzbIKHr_eJKDhUoZilZ7KUdplJe
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

df = pd.read_excel('/content/drive/MyDrive/aiml project /Final dataset.xlsx')


drop_columns = ['Full Name', 'Branch', 'Year', 'Suggested_Improvements']
df = df.drop(columns=drop_columns)

print(" Dataset loaded and unnecessary columns dropped.")
df.head()

target_columns = ['Google_Readiness', 'Amazon_Readiness', 'Infosys_Readiness', 'Microsoft_Readiness']


X = df.drop(columns=target_columns)
y = df[target_columns]


correlation_matrix = df.corr()


features_vs_targets = correlation_matrix.loc[X.columns, y.columns]


plt.figure(figsize=(14, 8))
sns.heatmap(features_vs_targets, annot=True, cmap='coolwarm', center=0)
plt.title('Feature-Target Correlation Heatmap')
plt.show()

models = {}

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error


if 'Google_Readiness' in df.columns:
    df = df.drop(columns=['Google_Readiness'])


weights_google = {
    'CGPA': 0.33,
    'Total Problems Solved': 0.30,
    'LeetCode Solved': 0.21
}
df['Google_Readiness'] = (
    df['CGPA'] * weights_google['CGPA'] +
    df['Total Problems Solved'] * weights_google['Total Problems Solved'] +
    df['LeetCode Solved'] * weights_google['LeetCode Solved']
)
df['Google_Readiness'] /= df['Google_Readiness'].max()

noise_scale = 0.15
df['Google_Readiness_noisy'] = (
    df['Google_Readiness'] +
    np.random.normal(0, noise_scale, len(df))
).clip(0, 1)


X = df[['CGPA', 'Total Problems Solved', 'LeetCode Solved']]
y = df['Google_Readiness_noisy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

google_model = LinearRegression().fit(X_train, y_train)
y_pred = google_model.predict(X_test)


print(f"R² Score: {r2_score(y_test, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.2f}")


models['Google'] = google_model


coeffs = pd.DataFrame({'Feature': X.columns, 'Coefficient': google_model.coef_})
print("\n Google Model Coefficients:")
print(coeffs)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

if 'Microsoft_Readiness' in df.columns:
    df = df.drop(columns=['Microsoft_Readiness'])


weights_microsoft = {
    'Technical Projects': 0.2,
    'Internships': 0.098,
    'Certifications': 0.14,
    'Total Problems Solved': 0.059,
    'Total Skills': 0.062
}
df['Microsoft_Readiness'] = (
    df['Technical Projects'] * weights_microsoft['Technical Projects'] +
    df['Internships'] * weights_microsoft['Internships'] +
    df['Certifications'] * weights_microsoft['Certifications'] +
    df['Total Problems Solved'] * weights_microsoft['Total Problems Solved'] +
    df['Total Skills'] * weights_microsoft['Total Skills']
)
df['Microsoft_Readiness'] /= df['Microsoft_Readiness'].max()


noise_scale = 0.12
df['Microsoft_Readiness_noisy'] = (
    df['Microsoft_Readiness'] +
    np.random.normal(0, noise_scale, len(df))
).clip(0, 1)


X = df[['Technical Projects', 'Internships', 'Certifications', 'Total Problems Solved', 'Total Skills']]
y = df['Microsoft_Readiness_noisy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


microsoft_model = LinearRegression().fit(X_train, y_train)
y_pred = microsoft_model.predict(X_test)


print(f"R² Score: {r2_score(y_test, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.2f}")


models['Microsoft'] = microsoft_model


coeffs = pd.DataFrame({'Feature': X.columns, 'Coefficient': microsoft_model.coef_})
print("\n Microsoft Model Coefficients:")
print(coeffs)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Drop old
if 'Amazon_Readiness' in df.columns:
    df = df.drop(columns=['Amazon_Readiness'])

# Recalc
weights_amazon = {
    'Technical Projects': 0.25,
    'Internships': 0.15,
    'Certifications': 0.18,
    'LeetCode Solved': 0.12,
    'Teamwork Experience': 0.1
}
df['Amazon_Readiness'] = (
    df['Technical Projects'] * weights_amazon['Technical Projects'] +
    df['Internships'] * weights_amazon['Internships'] +
    df['Certifications'] * weights_amazon['Certifications'] +
    df['LeetCode Solved'] * weights_amazon['LeetCode Solved'] +
    df['Teamwork Experience'] * weights_amazon['Teamwork Experience']
)
df['Amazon_Readiness'] /= df['Amazon_Readiness'].max()


noise_scale = 0.1
df['Amazon_Readiness_noisy'] = (
    df['Amazon_Readiness'] +
    np.random.normal(0, noise_scale, len(df))
).clip(0, 1)

# Train/Test
X = df[['Technical Projects', 'Internships', 'Certifications', 'LeetCode Solved', 'Teamwork Experience']]
y = df['Amazon_Readiness_noisy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit and Evaluate
amazon_model = LinearRegression().fit(X_train, y_train)
y_pred = amazon_model.predict(X_test)

print(f"R² Score: {r2_score(y_test, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.2f}")

# Save
models['Amazon'] = amazon_model

# Coefficients
coeffs = pd.DataFrame({'Feature': X.columns, 'Coefficient': amazon_model.coef_})
print("\n Amazon Model Coefficients:")
print(coeffs)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error


if 'Infosys_Readiness' in df.columns:
    df = df.drop(columns=['Infosys_Readiness'])


weights_infosys = {
    'Internships': 0.28,
    'Technical Projects': 0.2,
    'Certifications': 0.14,
    'LeetCode Solved': 0.15,
    'Teamwork Experience': 0.1
}
df['Infosys_Readiness'] = (
    df['Internships'] * weights_infosys['Internships'] +
    df['Technical Projects'] * weights_infosys['Technical Projects'] +
    df['Certifications'] * weights_infosys['Certifications'] +
    df['LeetCode Solved'] * weights_infosys['LeetCode Solved'] +
    df['Teamwork Experience'] * weights_infosys['Teamwork Experience']
)
df['Infosys_Readiness'] /= df['Infosys_Readiness'].max()

noise_scale = 0.09
df['Infosys_Readiness_noisy'] = (
    df['Infosys_Readiness'] +
    np.random.normal(0, noise_scale, len(df))
).clip(0, 1)


X = df[['Internships', 'Technical Projects', 'Certifications', 'LeetCode Solved', 'Teamwork Experience']]
y = df['Infosys_Readiness_noisy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


infosys_model = LinearRegression().fit(X_train, y_train)
y_pred = infosys_model.predict(X_test)

print("\n Infosys Model Performance with noise:")
print(f"R² Score: {r2_score(y_test, y_pred):.2f}")
print(f"MAE: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.2f}")


models['Infosys'] = infosys_model


coeffs = pd.DataFrame({'Feature': X.columns, 'Coefficient': infosys_model.coef_})
print("\n Infosys Model Coefficients:")
print(coeffs)

import pandas as pd


important_features = {
    'Google':   ['CGPA', 'Total Problems Solved', 'LeetCode Solved'],
    'Microsoft':['Technical Projects', 'Internships', 'Certifications', 'Total Problems Solved', 'Total Skills'],
    'Amazon':   ['Technical Projects', 'Internships', 'Certifications', 'LeetCode Solved', 'Teamwork Experience'],
    'Infosys':  ['Internships', 'Technical Projects', 'Certifications', 'LeetCode Solved', 'Teamwork Experience']
}

name = input("Enter your name: ")

while True:

    print("\nWhich company's readiness would you like to predict?")
    companies = list(models.keys())
    for i, comp in enumerate(companies, 1):
        print(f"{i}. {comp}")

    try:
        choice = int(input("Enter your choice number: "))
        if choice < 1 or choice > len(companies):
            print(f" Please enter a valid number between 1 and {len(companies)}.")
            continue
        company = companies[choice - 1]
    except ValueError:
        print(" Invalid input! Please enter a number.")
        continue


    user_data = {}
    for feature in important_features[company]:
        val = float(input(f"Enter your {feature}: "))
        user_data[feature] = val

    user_df = pd.DataFrame([user_data])


    model = models[company]
    readiness = model.predict(user_df)[0] * 100
    readiness = max(0, readiness)
    if readiness >= 100:
        print("\n You are almost ready! Just stay consistent and keep practicing!")
    else:
        print(f"\n Your predicted {company} Readiness: {readiness:.2f}%")


        if readiness < 30:
            suggestions = [
                "Focus on Data Structures & Algorithms (DSA)",
                "Solve at least 100 more coding problems"
            ]
        elif readiness < 50:
            suggestions = [
                "Work on 1–2 small technical projects",
                "Contribute to an open-source repository"
            ]
        elif readiness < 70:
            suggestions = [
                "Pursue one relevant internship",
                "Earn industry-recognized certifications"
            ]
        else:
            suggestions = [
                "Fine-tune your soft skills and communication",
                "Practice system design and mock interviews"
            ]

        print("\n Suggested Improvements:")
        for item in suggestions:
            print(f"- {item}")


    print("\n Would you like to check readiness for another company?")
    again = input("Enter 'yes' to continue or 'no' to exit: ").strip().lower()
    if again not in ('yes', 'y'):
        print(f"\n Goodbye, {name}! Best of luck with your preparations!")
        break









